name: 'northwind_inmon_project'
version: '1.0.0'
config-version: 2         # Adiciona explicitamente a vers達o do config, recomendado

profile: 'northwind_inmon_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  northwind_inmon_project:       # <== deve ser igual ao 'name' do topo do arquivo
    staging:
      +schema: staging           # Todos os models em models/staging/ v達o para schema 'staging'
      +materialized: view        # Best practice: staging como views
    integration:
      +schema: integration       # Todos os models em models/integration/ v達o para schema 'integration'
      +materialized: table       # Best practice: integration como tabelas
    presentation:
      +schema: presentation      # Todos os models em models/presentation/ v達o para schema 'presentation'
      +materialized: table       # Best practice: marts/presentation como tabelas
