version: 2

sources:
  - name: staging  
    database: NORTHWIND_EDW
    schema: STAGING
    tables:
      - name: CATEGORIES
      - name: CUSTOMERS
      - name: EMPLOYEES
      - name: ORDERS
      - name: ORDERS_DETAILS
      - name: PRODUCTS
      - name: REGIONS
      - name: SHIPPERS
      - name: SUPPLIERS
      - name: TERRITORIES
      - name: EMPLOYEE_TERRITORIES
